Metrics/AbcSize:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Enabled: false
  
Metrics/BlockLength:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
