#!/usr/bin/env ruby

flag = false

staged_files = `git diff --cached --name-only`.split

ruby_files = staged_files.select{|s| s =~ /\.rb$/}

ruby_files.each do |file|
  result = system("ruby >/dev/null -c #{file}")
  flag = true if !result
end

abort("Failed syntax check. Fix and recommit.") if flag

puts "All staged files passed syntax check. Continuing commit..."
